name: Build

on:
  push:
  pull_request:
  
jobs:
  lint:
    name: Reviewdog Lint
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      - 
        name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
          
  test:
    name: Test and Cover
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v1
      - 
        name: Run Unit tests
        run: go test -coverprofile=coverage.txt ./...
      - 
        name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
